name: Run Tests

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
      working-directory: ./backend

    - name: Print Node.js version
      run: node -v
      working-directory: ./backend

    - name: Print npm version
      run: npm -v
      working-directory: ./backend

    - name: List project files
      run: ls -la
      working-directory: ./backend

    - name: Run tests
      run: npm test
      working-directory: ./backend
